import Header from "@/components/Header";
import SubHeader from "@/components/SubHeader";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Cormorant_Garamond, Jost } from "next/font/google";
import "./globals.css";
const jost = Jost({
  subsets: ["latin"],
  variable: "--Jost",
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

const cormorant_garamond = Cormorant_Garamond({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-cormorant_garamond",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${cormorant_garamond.className} ${jost.className}`}>
        <SubHeader />
        <Header />
        {children}
      </body>
    </html>
  );
}
